### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by jacobmcilravey** [proxikal/DiscordPHPBot#1]
Followed the linux tutorial, seemed everything went fine and dandy. Realized not a single .sh file is present in the project. Both in the repo and from the link listed in the Linux tutorial.

**Comment by DoNotSpamPls** [comment]
We will look into it.
Check the repo frequently for new files ;)

**Comment by jacobmcilravey** [comment]
Thanks! Great work with the bot guys, it looks great! I just wish I could
use it ;)

On Sat, Mar 19, 2016, 5:40 AM DoNotSpamPls <notifications@github.com> wrote:

> We will look into it.
> Check the repo frequently for new files ;)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/proxikal/DiscordPHPBot/issues/1#issuecomment-198695221>
>
-- 

Thanks,

-------------
Jake McIlravey

**Comment by EdibleDerpy** [comment]
I'm writing a tutorial on PM2 right now i personally use PM2 to host my bot because it's more persistent.

**Comment by jacobmcilravey** [comment]
I'm currently using DigitalOcean to run my bots. But this one really caught my eye. I'll check the updated tutorial and see if it works for me, and I'll follow up here.

**Comment by EdibleDerpy** [comment]
Alright we have added a turorial for PM2 which you can read and follow here [PM2 Tutorial](https://github.com/proxikal/DiscordPHPBot/wiki/Install-PM2-on-Your-Ubuntu-Server)

**Thread Closed**

**Comment by jacobmcilravey** [comment]
Thanks everyone. You guys do and did a wonderful job :)

**Comment by proxikal** [comment]
Hopefully I will have a better version updated to github in the next few days! Keep checking back for 3.0.0 :)
